DROP DATABASE IF EXISTS `QLTTNN`;
CREATE DATABASE `QLTTNN`;
USE `QLTTNN`;

DROP TABLE IF EXISTS `COURSE`;
CREATE TABLE `COURSE` (
	`ID` INT AUTO_INCREMENT NOT NULL,
	`NAME` NVARCHAR(30) NOT NULL,
	`TIMESTART` DATE NOT NULL, 
	`TIMEEND` DATE NOT NULL, 
	`COURSEFEE` DOUBLE NOT NULL,
    PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE `EMPLOYEE` (
	`ID` NVARCHAR(10) NOT NULL,
	`NAME` NVARCHAR(10) NOT NULL,
	`PASSWORD` NVARCHAR(20) NOT NULL,
	`PHONENUMBER` NVARCHAR(11) NOT NULL,
	`EMAIL` NVARCHAR(30) DEFAULT NULL,
	`ADDRESS` NVARCHAR(50) NOT NULL,
	`TYPE` INT NOT NULL,
    PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `STUDENT`;
CREATE TABLE `STUDENT` (
	`MSSV` NVARCHAR(10) NOT NULL,
	`NAME` NVARCHAR(10) NOT NULL,
	`PASSWORD` NVARCHAR(20) NOT NULL,
	`PHONENUMBER` NVARCHAR(11) NOT NULL,
	`EMAIL` NVARCHAR(30) DEFAULT NULL,
	`NGAYSINH` DATE NOT NULL,
    PRIMARY KEY (`MSSV`)
);

DROP TABLE IF EXISTS `MANAGER`;
CREATE TABLE `MANAGER` (
	`IDMANAGER` NVARCHAR(10) NOT NULL,
	`IDEMPLOYEE` NVARCHAR(10) NOT NULL,
    PRIMARY KEY (`IDMANAGER`, `IDEMPLOYEE`)
);

DROP TABLE IF EXISTS `NOTIFICATION`;
CREATE TABLE `NOTIFICATION` (
	`ID` INT AUTO_INCREMENT NOT NULL, 
	`IDTEACHER` NVARCHAR(10) NOT NULL,
	`IDCOURSE` INT NOT NULL, 
	`CONTENT` NVARCHAR(255) NOT NULL,
	`TIME` DATETIME NOT NULL,
    PRIMARY KEY (`ID`)
);

